spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource: # DATABASE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NM}
    password: ${DB_PW}

  jpa: # JPA
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8090
#  ssl:
#    key-store: ${KEY_STORE}
#    key-store-type: PKCS12
#    key-alias: ${KEY_ALIAS}
#    key-store-password: ${KEY_STORE_PASSWORD}
  error:
    include-exception: true     # ??? exception? ??? ???? ??
    path: '/error'               # ??? ??? Handler? ??
    whitelabel:
      enabled: true             # ?? ?? ??? ????? ??? ?? ??? ?? ??

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: sehoawsbucket
    region:
      static: ap-southeast-2
    stack:
      auto: false

#file:
#  upload-dir: src/main/resources/static/images/